#!/usr/bin/env python
import sys

sys.path.append('../')

import credentials as cd

import pyetrade

consumer_key = cd.CONSUMER_KEY
consumer_secret = cd.SECRET_KEY
tokens = {'oauth_token': cd.OAUTH_TOKEN,
    'oauth_token_secret': cd.OAUTH_TOKEN_SECRET}

accounts = pyetrade.ETradeAccounts(
        consumer_key,
        consumer_secret,
        tokens['oauth_token'],
        tokens['oauth_token_secret'],
        dev=True
        )

print(accounts.list_accounts())
